/**
 * Kompletní seznam gemů pro Google Gemini.
 * Každý gem má slug pro URL, emoji, názvy a popisy v češtině.
 */
window.GEMS_DATA = {
  "3-step-reflection": {
    slug: "3-step-reflection",
    emoji: "🪞",
    title: "3-Step Reflection",
    titleCs: "3-kroková reflexe",
    shortDescCs: "Strukturovaná reflexe podle Rolfe et al. – Co?, Tak co?, Co dál?",
    descriptionCs: "Tento Gem vede žáky k hlubší a smysluplné reflexi vlastního učení. Opírá se o model Rolfe et al. a pomocí sokratovského způsobu dotazování pomáhá žákům promýšlet jejich zkušenost krok za krokem – od otázky „Co?“ přes „Tak co?“ až po „Co dál?“. Cílem je překročit stručné či povrchní odpovědi a podpořit skutečné porozumění tomu, co žák dělal, co si z činnosti odnáší a jak může získané poznatky využít v dalším učení. Žák nejprve zadá svůj ročník a popíše aktivitu, projekt nebo zkušenost, kterou chce reflektovat. Gemini potom vede navazující rozhovor, klade doplňující otázky podle hloubky odpovědí a na závěr vytvoří souvislé shrnutí reflexe, které je připravené k odevzdání.",
    category: "student",
    categories: ["student", "newest"],
    gemUrl: "https://gemini.google.com/gem/18paOMiUpKKkK7n0P_Xd4pk2gWHfYV7qz?usp=sharing"
  },
  "3d-ngss-activity": {
    slug: "3d-ngss-activity",
    emoji: "🔬",
    title: "Přírodovědný architekt",
    titleCs: "Přírodovědný architekt",
    shortDescCs: "Materiály do přírodopisu podle českého kurikula.",
    descriptionCs: "Tento Gem pomáhá učitelům rychle připravovat materiály do přírodopisu a přírodovědných předmětů podle českého kurikula. Z učiva a očekávaných výstupů vytváří použitelné aktivity, otázky, pracovní úkoly i hodnoticí podklady pro výuku.",
    category: "stem",
    categories: ["stem", "newest"],
    gemUrl: "https://gemini.google.com/gem/1BVCe32HYtWMpM9_WVzxv1N37zCjbp8Tv?usp=sharing"
  },
  "5e-lesson-plan": {
    slug: "5e-lesson-plan",
    emoji: "🖐️",
    title: "5E Lesson Plan",
    titleCs: "5E plán hodiny",
    shortDescCs: "Strukturovaný plán podle modelu 5E (Zapoj, Prozkoumej, Vysvětli, Rozšiř, Zhodnoť).",
    descriptionCs: "Tento Gem pomáhá učitelům rychle připravit promyšlený plán hodiny podle badatelského modelu 5E. Vychází z cílů výuky, očekávaných výstupů a potřeb konkrétní třídy, takže pomáhá vytvářet výuku, která je aktivní, srozumitelná a přiměřená věku žáků. Učitel zadá ročník, předmět, téma, cíle a délku hodiny, Gemini se doptá na úroveň žáků, dostupné pomůcky a technologie a poté vytvoří strukturovaný plán hodiny rozdělený do fází Zapojení, Zkoumání, Vysvětlení, Rozšíření a Zhodnocení. Součástí výstupu jsou také materiály a konkrétní návrhy aktivit pro jednotlivé části hodiny.",
    category: "planning",
    categories: ["planning", "newest"],
    gemUrl: "https://gemini.google.com/gem/16DKeFPD1_wKL4Odd_7ypC2QMsxGbbN5K?usp=sharing"
  },
  "ai-use-reflection": {
    slug: "ai-use-reflection",
    emoji: "🤖",
    title: "Reflexe spolupráce s AI",
    titleCs: "Reflexe spolupráce s AI",
    shortDescCs: "Reflexe spolupráce s AI při projektové práci.",
    descriptionCs: "Tento Gem pomáhá žákům přesně popsat, jak při projektu spolupracovali s AI, a podporuje je v přechodu od pasivního využívání nástrojů k aktivní a vědomé tvorbě. Jako průvodce reflexí spolupráce s AI využívá rámec „Vlastní práce – Role AI – Reflexe“, který žáky vede k pojmenování jejich vlastního podílu, porozumění roli AI a hlubšímu promýšlení celého procesu.",
    category: "student",
    categories: ["student", "newest"],
    gemUrl: "https://gemini.google.com/gem/18SbMO32LtNwW-J5ZE-i8IJ8xKJ_oBueO?usp=sharing"
  },
  "book-matchmaker": {
    slug: "book-matchmaker",
    emoji: "❤️",
    title: "Book Matchmaker",
    titleCs: "Doporučovač knih",
    shortDescCs: "Doporučení knih podle zájmů, věku a čtenářské úrovně.",
    descriptionCs: "Tento Gem pomáhá žákům najít další knihu, která je opravdu zaujme. Nezůstává jen u základních žánrů, ale vychází i z jejich širších zájmů, například oblíbených filmů, videoher nebo koníčků. Doporučuje knihy tak, aby odpovídaly čtenářské úrovni i věku a tématické vyspělosti žáka.",
    category: "literacy",
    categories: ["literacy", "student", "newest"],
    gemUrl: "https://gemini.google.com/gem/1oCkC2HNKlsEVANNRfTJ0-nA1nT7Nlh-q?usp=sharing"
  },
  "cognates-false-friends": {
    slug: "cognates-false-friends",
    emoji: "🌐",
    title: "Cognates & False Friends",
    titleCs: "Kognáty a falešní přátelé",
    shortDescCs: "Práce s podobnými slovy v cizích jazycích.",
    descriptionCs: "Tento Gem pomáhá učitelům cizích jazyků i žákům rozpoznávat a vysvětlovat kognáty a falešné přátele v zadaném textu. Přizpůsobuje slovní zásobu, způsob vysvětlení i obtížnost věku a jazykové úrovni žáka.",
    category: "literacy",
    categories: ["literacy", "newest"],
    gemUrl: "https://gemini.google.com/gem/12RONf5LSIsEvCaPqng_NhFYmrs7PAbC0?usp=sharing"
  },
  "cte-client-simulator": {
    slug: "cte-client-simulator",
    emoji: "🗣️",
    title: "CTE Client Simulator",
    titleCs: "Simulátor zákazníka a klienta",
    shortDescCs: "Simulace komunikace se zákazníkem nebo klientem.",
    descriptionCs: "Gem pomáhá žákům odborných škol nacvičovat komunikaci se zákazníkem nebo klientem, zjišťování problému a správný postup v modelových situacích. V roli virtuální postavy reaguje na způsob komunikace žáka a po skončení poskytne konkrétní zpětnou vazbu.",
    category: "student",
    categories: ["student", "engagement", "newest"],
    gemUrl: "https://gemini.google.com/gem/1gJ1Mh78XrG3FPhrto7wn81wqrYSBO965?usp=sharing"
  },
  "deca-role-play-sim": {
    slug: "deca-role-play-sim",
    emoji: "🗣️",
    title: "DECA Role-Play Sim",
    titleCs: "Obchodní simulační hra",
    shortDescCs: "Obchodní, marketingové a profesní role-play simulace.",
    descriptionCs: "Tento Gem pomáhá žákům trénovat improvizované obchodní, marketingové a profesní role-play situace pomocí realistických scénářů, doplňujících otázek a konkrétní zpětné vazby k vystupování, argumentaci a návrhu řešení.",
    category: "student",
    categories: ["student", "engagement", "newest"],
    gemUrl: "https://gemini.google.com/gem/1VyFkyajinU4LCY6Ni7Rb4LjEuW46Eoa4?usp=sharing"
  },
  "edtech-tool-evaluator": {
    slug: "edtech-tool-evaluator",
    emoji: "🛡️",
    title: "EdTech Tool Evaluator",
    titleCs: "Hodnotitel digitálních nástrojů",
    shortDescCs: "Hodnocení digitálních nástrojů před zavedením do výuky.",
    descriptionCs: "Tento Gem pomáhá učitelům a školám posoudit digitální nástroje ještě před jejich zavedením do výuky, aby byly pedagogicky přínosné, přístupné pro různé žáky a bezpečné z hlediska ochrany osobních údajů.",
    category: "professional",
    categories: ["professional", "newest"],
    gemUrl: "https://gemini.google.com/gem/1KPRcRlnac54rSOCEn4gi5AunuV7118Bq?usp=sharing"
  },
  "educational-map-maker": {
    slug: "educational-map-maker",
    emoji: "🗺️",
    title: "Educational Map Maker",
    titleCs: "Vzdělávací mapa",
    shortDescCs: "Interaktivní mapy z libovolného tématu pro Google My Maps.",
    descriptionCs: "Tento Gem pomáhá učitelům i žákům rychle převést libovolné téma – od historických událostí po literární díla nebo přírodopisná místa – do vlastní interaktivní mapy. Automaticky připraví přehled míst, souřadnic a doprovodných informací a vygeneruje datovou sadu, kterou lze snadno použít v Google My Maps.",
    category: "materials",
    categories: ["materials", "newest"],
    gemUrl: "https://gemini.google.com/gem/1w0n5eUizpYwyF97Ike4YV3AMWLR3Mv7P?usp=sharing"
  },
  "exit-ticket": {
    slug: "exit-ticket",
    emoji: "🎫",
    title: "Exit Ticket",
    titleCs: "Výstupní lístek (Exit Ticket)",
    shortDescCs: "Výstupní lístky pro ověření porozumění na konci hodiny.",
    descriptionCs: "Tento Gem pomáhá rychle vytvářet kvalitní a cílené výstupní lístky pro ověření porozumění žáků na konci libovolné hodiny. Jako praktický asistent učitele zajišťuje, aby úkoly odpovídaly probíranému učivu, ročníku i očekávaným výstupům a cílům výuky v rámci RVP a ŠVP. Je ideální pro získání rychlé zpětné vazby, odhalení nejasností a lepší plánování další výuky bez zbytečného navyšování příprav.",
    category: "assessment",
    categories: ["assessment", "newest"],
    gemUrl: "https://gemini.google.com/gem/1Rk_-JDUGJcLtIVMbAlsAYOxw4jN_otLz?usp=sharing"
  },
  "grading-partner": {
    slug: "grading-partner",
    emoji: "💯",
    title: "Grading Partner",
    titleCs: "Asistent hodnocení",
    shortDescCs: "Pomocník při hodnocení žákovských prací a zpětné vazbě.",
    descriptionCs: "Tento Gem je pomocník pro učitele při hodnocení žákovských prací. Podle zadaných kritérií nebo rubriky připraví přehledné slovní hodnocení pro učitele a zároveň srozumitelnou, věkově přiměřenou zpětnou vazbu pro žáka, kterou lze dál upravit a použít v praxi.",
    category: "assessment",
    categories: ["assessment", "newest"],
    gemUrl: "https://gemini.google.com/gem/1B3Eal0ZGy5eUCOvk5Ewq-ARGGPfEZSyH?usp=sharing"
  },
  "job-interview-coach": {
    slug: "job-interview-coach",
    emoji: "🤝",
    title: "Job Interview Coach",
    titleCs: "Pracovní pohovor nanečisto",
    shortDescCs: "Nácvik pracovního pohovoru s konkrétní zpětnou vazbou.",
    descriptionCs: "Tento Gem pomáhá žákům připravit se na pracovní pohovor, posílit sebevědomí a zlepšit komunikační dovednosti. Funguje jako přátelský a podporující kouč, který vede realistický nácvik pohovoru a potom poskytuje konkrétní a srozumitelnou zpětnou vazbu k odpovědím, vystupování i celkovému dojmu.",
    category: "student",
    categories: ["student", "newest"],
    gemUrl: "https://gemini.google.com/gem/1ppi62C1-w6D9Bnghza7XqL_b6YPszgL8?usp=sharing"
  },
  "kwl-interactive": {
    slug: "kwl-interactive",
    emoji: "🤔",
    title: "KWL Interactive",
    titleCs: "Vím – Chci vědět – Naučil/a jsem se",
    shortDescCs: "Metoda KWL pro aktivní učení a reflexi napříč předměty.",
    descriptionCs: "Tento Gem pomáhá žákům pracovat s metodou KWL (Vím – Chci vědět – Naučil/a jsem se), aby si lépe ujasnili, co už o tématu vědí, co se chtějí dozvědět a co si z učení skutečně odnesli. Jako trpělivý průvodce podporuje aktivní učení, čtenářské porozumění, kladení otázek i závěrečnou reflexi a je vhodný pro práci napříč předměty na základní i střední škole.",
    category: "student",
    categories: ["student", "newest"],
    gemUrl: "https://gemini.google.com/gem/1m6GNfzeT70dsH_r5-gzHXpGPvMv2M-W_?usp=sharing"
  },
  "mindfulness-break": {
    slug: "mindfulness-break",
    emoji: "🧘",
    title: "Mindfulness Break",
    titleCs: "Minuta pro sebe",
    shortDescCs: "Krátké mindfulness pauzy na 1–3 minuty pro zklidnění a soustředění.",
    descriptionCs: "Tento Gem nabízí žákům i učitelům krátké mindfulness pauzy, které pomáhají zklidnit se, uvolnit napětí a znovu se soustředit během školního dne. Pomocí jednoduchých cvičení na 1–3 minuty provází uživatele podle toho, zda potřebují zvládnout stres, únavu, neklid nebo jen krátce vypnout a nadechnout se.",
    category: "professional",
    categories: ["professional", "newest"],
    gemUrl: "https://gemini.google.com/gem/14q6JWgAANCMgOsNmf5BlLZcqGcY4lEIv?usp=sharing"
  },
  "musailab": {
    slug: "musailab",
    emoji: "🎹",
    title: "MusAILab",
    titleCs: "Hudební AI dílna",
    shortDescCs: "Materiály pro hudební výchovu s ohledem na české prostředí.",
    descriptionCs: "Tento Gem pomáhá učitelům vytvářet nápadité, inkluzivní a prakticky využitelné materiály pro hudební výchovu. Jako AI asistent pro učitele hudby převádí vaše základní nápady do přehledných výukových aktivit a materiálů připravených pro použití ve výuce, a to s ohledem na české školní prostředí, tvořivé činnosti, aktivní zapojení žáků i smysluplné využití digitálních hudebních nástrojů.",
    category: "materials",
    categories: ["materials", "newest"],
    gemUrl: "https://gemini.google.com/gem/13NPh-egAGYjuERWu_X8-w-NPlWRPkJ5H?usp=sharing"
  },
  "pe-game-inventor": {
    slug: "pe-game-inventor",
    emoji: "⚽",
    title: "PE Game Inventor",
    titleCs: "Tvůrce her do tělocviku",
    shortDescCs: "Rychlé vymýšlení her pro tělesnou výchovu podle podmínek.",
    descriptionCs: "Tento Gem pomáhá učitelům tělesné výchovy rychle vymýšlet nové, zábavné a věkově vhodné hry podle konkrétních podmínek ve výuce. Funguje jako kreativní a bezpečnostně zaměřený pomocník, který navrhuje snadno upravitelné aktivity s ohledem na prostor, počet žáků, dostupné pomůcky i potřebu udržet přehled, zapojení a bezpečí celé třídy.",
    category: "engagement",
    categories: ["engagement", "newest"],
    gemUrl: "https://gemini.google.com/gem/1qcoyRDRUIMEu7_WWwPXlNTp15FEIDdNG?usp=sharing"
  },
  "professional-learning-coach": {
    slug: "professional-learning-coach",
    emoji: "📣",
    title: "Professional Learning Coach",
    titleCs: "Pedagogický mentor",
    shortDescCs: "Plánování profesního růstu po menších krocích.",
    descriptionCs: "Tento Gem pomáhá učitelům plánovat a rozvíjet profesní růst po menších, zvládnutelných krocích. Jako pedagogický mentor propojuje ověřené poznatky z výzkumu s každodenní školní praxí a podporuje vás při zavádění přístupů, jako je čtenářská gramotnost, formativní hodnocení, individualizace výuky, UDL nebo systém podpory žáků, v souladu s potřebami české školy a profesním rozvojem pedagoga.",
    category: "professional",
    categories: ["professional", "newest"],
    gemUrl: "https://gemini.google.com/gem/179E_WE_3mnBfjCl68H72-QQ-6ng4HVQ9?usp=sharing"
  },
  "raft-writing-prompts": {
    slug: "raft-writing-prompts",
    emoji: "✍️",
    title: "RAFT Writing Prompts",
    titleCs: "RAFT generátor psacích úkolů",
    shortDescCs: "Kreativní psací úkoly RAFT (Role, Publikum, Formát, Téma).",
    descriptionCs: "Tento asistent pomáhá učitelům rychle vymýšlet kreativní a poutavé psací úkoly typu RAFT (Role, Publikum, Formát, Téma), které odpovídají věku žáků, výukovým cílům i konkrétnímu předmětu.",
    category: "literacy",
    categories: ["literacy", "newest"],
    gemUrl: "https://gemini.google.com/gem/1SEWs0hCmvHjZzmy8jDH6EaBk9-7bnDGs?usp=sharing"
  },
  "shelf-talkers": {
    slug: "shelf-talkers",
    emoji: "📣",
    title: "Shelf-Talkers",
    titleCs: "Knižní lákadla",
    shortDescCs: "Krátké úderné texty ke knihám pro školní knihovnu.",
    descriptionCs: "Tento Gem pomáhá rychle vytvářet krátké, úderné texty ke knihám, které zaujmou žáky a podpoří jejich samostatný výběr četby ve školní či třídní knihovně. Jako tvořivý průvodce čtenářstvím pracuje s příběhem, žánrem a atmosférou knihy a připravuje několik různých variant textu přizpůsobených věku a zájmům cílových čtenářů.",
    category: "literacy",
    categories: ["literacy", "newest"],
    gemUrl: "https://gemini.google.com/gem/1iBs07GvX2298xH7QoS1ju6dKbsVTCSRX?usp=sharing"
  },
  "simple-slides": {
    slug: "simple-slides",
    emoji: "🎯",
    title: "Simple Slides",
    titleCs: "Srozumitelné slidy",
    shortDescCs: "Prezentace s nízkou kognitivní zátěží pro různorodé žáky.",
    descriptionCs: "Tento Gem pomáhá rychle převádět složitá témata, texty, vzdělávací cíle nebo články do přehledných prezentací s nízkou kognitivní zátěží pro různorodé žáky. Každý slide staví na jedné klíčové myšlence, pracuje s minimem textu a využívá konkrétní vizuální opory, aby snižoval bariéry v porozumění a usnadňoval učení.",
    category: "materials",
    categories: ["materials", "support", "newest"],
    gemUrl: "https://gemini.google.com/gem/1Rp3i2_GWUDbpGerZGxSAPDmXCW5mh9EY?usp=sharing"
  },
  "student-assignment-feedback": {
    slug: "student-assignment-feedback",
    emoji: "⭐",
    title: "Student Assignment Feedback",
    titleCs: "Průvodce zpětnou vazbou",
    shortDescCs: "Jasná zpětná vazba k práci před odevzdáním.",
    descriptionCs: "Tento Gem pomáhá žákům zlepšit jejich práci před odevzdáním tím, že jim poskytuje jasnou a konstruktivní zpětnou vazbu podle zadaných kritérií, upozorňuje na silné stránky i rezervy a podporuje samostatnost bez toho, aby úkol vypracoval za ně.",
    category: "assessment",
    categories: ["assessment", "student", "newest"],
    gemUrl: "https://gemini.google.com/gem/1iLbjXOt84UzzXKX4u77k4rU0mpFGQg1p?usp=sharing"
  },
  "teach-a-robot": {
    slug: "teach-a-robot",
    emoji: "🤖",
    title: "Teach a Robot",
    titleCs: "Uč mě, robote",
    shortDescCs: "Žáci vysvětlují učivo robotovi pro prohloubení porozumění.",
    descriptionCs: "Tento Gem pomáhá žákům upevnit a prohloubit učivo tím, že obrací běžné role: místo aby AI učila je, žáci učí AI. V roli zvídavého, přátelského, ale občas zmateného „robota“ vede žáky k tomu, aby vysvětlovali učivo vlastními slovy, zpřesňovali své myšlení a opravovali vzniklá nedorozumění. Robot záměrně přichází s typickými chybami a mylnými představami, například se záměnou pojmů, unáhleným zobecněním nebo chybným vysvětlením souvislostí, takže si žák učivo skutečně promyslí do hloubky.",
    category: "student",
    categories: ["student", "engagement", "newest"],
    gemUrl: "https://gemini.google.com/gem/1UYnDQ_Gy5yLti-AhJr0DWKXbRCL3lxxo?usp=sharing"
  },
  "transition-portfolio": {
    slug: "transition-portfolio",
    emoji: "🎓",
    title: "Transition Portfolio",
    titleCs: "Portfolio přechodu žáka",
    shortDescCs: "Hodnocení přechodu žáka a cíle vzdělávání v českém prostředí.",
    descriptionCs: "Tento Gem pomáhá systematicky vést hodnocení přechodu žáka na základě jeho silných stránek, preferencí, zájmů a podpůrných potřeb a převádět tyto informace do konkrétních vzdělávacích, profesních a osobních cílů v souladu s českým školským prostředím. Jako zkušený a empatický kariérový poradce a pedagogický průvodce přizpůsobuje jazyk podle toho, zda komunikuje s pedagogem, poradenským pracovníkem, rodičem nebo přímo se žákem, a pomáhá formulovat realistické, srozumitelné a na žáka zaměřené kroky pro další studium, odborný rozvoj i vstup do pracovního života.",
    category: "student",
    categories: ["student", "support", "newest"],
    gemUrl: "https://gemini.google.com/gem/1QQax5FBD36yZ4le-R_UdBS_NGvaStByq?usp=sharing"
  },
  "accelerated-learning": {
    slug: "accelerated-learning",
    emoji: "🚀",
    title: "Accelerated Learning",
    titleCs: "Zrychlené učení",
    shortDescCs: "Lekce využívající principy kognitivních věd.",
    descriptionCs: "Tento Gem pomáhá navrhovat náročné, kvalitní rozšiřující aktivity pro pokročilé žáky, kteří již zvládli současný obsah. Jako specialista na nadané a diferenciaci vytváří přizpůsobené plány pro vertikální akceleraci (následující ročník) nebo horizontální obohacení (hlubší složitost) a nabízí vygenerování Smlouvy o učení žáka pro zajištění samostatné autonomie žáka.",
    category: "planning",
    categories: ["planning"],
    gemUrl: "https://www.edugems.ai/gem/accelerated-learning"
  },
  "ai-samr-activity": {
    slug: "ai-samr-activity",
    emoji: "🤖",
    title: "AI + SAMR Activity",
    titleCs: "AI + SAMR aktivita",
    shortDescCs: "Aktivity integrující AI podle SAMR modelu.",
    descriptionCs: "Tento Gem pomáhá navrhovat učební zkušenosti, v nichž je AI používána bezpečně, eticky a efektivně k posílení žáků. Zakotven v „AI optimismu“ využívá model SAMR k rozšíření standardních hodin na příležitosti, kde AI funguje nejen jako nástroj, ale jako myšlenkový partner (Modifikace) nebo spoluhráč/spolutvůrce (Redefinice) pro maximalizaci žákovské agentury.",
    category: "planning",
    categories: ["planning"],
    gemUrl: "https://www.edugems.ai/gem/ai-samr-activity"
  },
  "bell-ringer-by-date": {
    slug: "bell-ringer-by-date",
    emoji: "🔔",
    title: "Bell Ringer by Date",
    titleCs: "Zahřívací aktivita podle data",
    shortDescCs: "Krátké úvodní aktivity podle historického data.",
    descriptionCs: "Tento Gem pomáhá začínat každou hodinu energií a relevancí generováním včasné „zahřívací aktivity podle data“. Jako expertní specialista na zapojení žáků propojuje historické události, svátky nebo zajímavosti daného dne přímo s vaším předmětem (např. propojení „Národního dne pizzy“ se zlomky v hodině matematiky) a zároveň zajišťuje, že veškerý obsah je přiměřený ročníku a „bezpečný pro školu\“.",
    category: "planning",
    categories: ["planning", "engagement"],
    gemUrl: "https://www.edugems.ai/gem/bell-ringer-by-date"
  },
  "choice-board": {
    slug: "choice-board",
    emoji: "🔠",
    title: "Choice Board",
    titleCs: "Výběrová tabule",
    shortDescCs: "Tabulka výběrových aktivit pro žáky.",
    descriptionCs: "Tento Gem pomáhá rychle generovat podrobnou, přístupnou a poutavou výběrovou tabuli pro libovolný žákovský úkol. Navržen specialistou na UDL nabízí maximální žákovskou agenturu a různou náročnost tím, že zahrnuje možnosti napříč třemi principy UDL: Reprezentace, Akce a vyjadřování a Zapojení.",
    category: "planning",
    categories: ["planning", "support"],
    gemUrl: "https://www.edugems.ai/gem/choice-board"
  },
  "class-syllabus": {
    slug: "class-syllabus",
    emoji: "📄",
    title: "Class Syllabus",
    titleCs: "Sylabus předmětu",
    shortDescCs: "Tvorba sylabu kurzu.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit podrobný a přizpůsobený sylabus pro jasnou komunikaci vaší učební cesty, očekávání a pravidel. Ideální pro uvedení žáků a rodin do vaší hodiny a zajištění hladkého začátku školního roku s jasným, snadno čitelným dokumentem.",
    category: "planning",
    categories: ["planning"],
    gemUrl: "https://www.edugems.ai/gem/class-syllabus"
  },
  "emergency-sub-plan": {
    slug: "emergency-sub-plan",
    emoji: "🚨",
    title: "Emergency Sub Plan",
    titleCs: "Nouzový plán pro suplování",
    shortDescCs: "Plán hodiny pro náhradní učitele.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat podrobný, nenáročný na přípravu a samostatný nouzový plán pro suplování. Ideální pro vytváření „neprůstřelných\“ hodin při neočekávaných absencích, zajišťuje, že plán těsně odpovídá vašemu obsahu, ale nevyžaduje žádná specifická přihlášení, složitou technologii ani specializované znalosti od náhradního učitele.",
    category: "planning",
    categories: ["planning", "professional"],
    gemUrl: "https://www.edugems.ai/gem/emergency-sub-plan"
  },
  "field-trip-plan": {
    slug: "field-trip-plan",
    emoji: "🚌",
    title: "Field Trip Plan",
    titleCs: "Plán exkurze",
    shortDescCs: "Plánování školních výletů a exkurzí.",
    descriptionCs: "Tento Gem pomáhá rychle naplánovat kreativní, spolehlivou a poutavou exkurzi, která zajistí, že žáci prožijí své učení v reálném světě. Ideální pro navrhování zážitkových, praktických učebních aktivit s konkrétní destinací a poskytuje vše potřebné pro úspěšný výlet.",
    category: "planning",
    categories: ["planning", "professional"],
    gemUrl: "https://www.edugems.ai/gem/field-trip-plan"
  },
  "jigsaw-activity": {
    slug: "jigsaw-activity",
    emoji: "🧩",
    title: "Jigsaw Activity",
    titleCs: "Jigsaw aktivita",
    shortDescCs: "Skupinová aktivita metodou jigsaw.",
    descriptionCs: "Tento Gem pomáhá rychle navrhnout bohatou, kolaborativní jigsaw aktivitu na libovolné téma nebo učební cíl. Poskytuje podrobné instrukce včetně diskusních podnětů pro závěrečnou reflexi a doporučených materiálů pro aktivitu, aby vaše hodina podporovala hluboké porozumění prostřednictvím mistrovství expertních skupin a výuky žák-žák.",
    category: "planning",
    categories: ["planning"],
    gemUrl: "https://www.edugems.ai/gem/jigsaw-activity"
  },
  "lesson-hooks": {
    slug: "lesson-hooks",
    emoji: "🪝",
    title: "Lesson Hooks",
    titleCs: "Motivační háčky lekce",
    shortDescCs: "Nápady na úvodní motivaci hodiny.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit 3 až 5 vysoce účinných, novátorských a poutavých motivačních háčků (otázky, krátké aktivity, vizuály nebo relevantní scénáře), které těsně odpovídají konkrétnímu učebnímu cíli nebo tématu. Ideální pro zvládnutí strategií motivace a upoutání pozornosti, které roznítí skutečnou zvědavost a efektivně připraví žáky na následující obsah.",
    category: "planning",
    categories: ["planning", "engagement"],
    gemUrl: "https://www.edugems.ai/gem/lesson-hooks"
  },
  "lesson-plan": {
    slug: "lesson-plan",
    emoji: "📋",
    title: "Lesson Plan",
    titleCs: "Plán hodiny",
    shortDescCs: "Obecný plán hodiny.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat podrobný, na standardy navázaný a vývojově přiměřený plán hodiny. Zajišťuje, že plán obsahuje jasné instrukce, strategie diferenciace a vhodné hodnocení, vše přizpůsobené kontextu vaší třídy.",
    category: "planning",
    categories: ["planning"],
    gemUrl: "https://www.edugems.ai/gem/lesson-plan"
  },
  "real-world-examples": {
    slug: "real-world-examples",
    emoji: "🌎",
    title: "Real World Examples",
    titleCs: "Příklady z reálného světa",
    shortDescCs: "Reálné příklady pro výuku.",
    descriptionCs: "Tento Gem pomáhá rychle brainstormovat 3 relevantní, konkrétní a autentické reálné souvislosti (tj. konkrétní současné nebo historické události nebo příběhy z médií přiměřené věku) pro libovolné akademické téma nebo učební cíl. Ideální pro vyhýbání se obecným nebo hypotetickým scénářům a zajištění, že vaše hodiny jsou zakotveny v smysluplných, ne povrchních příkladech, které podporují zapojení žáků.",
    category: "planning",
    categories: ["planning"],
    gemUrl: "https://www.edugems.ai/gem/real-world-examples"
  },
  "standards-unpacker": {
    slug: "standards-unpacker",
    emoji: "📦",
    title: "Standards Unpacker",
    titleCs: "Rozbory standardů",
    shortDescCs: "Rozbor vzdělávacích standardů.",
    descriptionCs: "Tento Gem pomáhá převádět složité akademické standardy na využitelné, pro třídu připravené součásti hodiny. Jako expertní návrhář kurikula rozkládá konkrétní standardy na jejich podstatné dovednosti (slovesa), znalosti (podstatná jména) a koncepty a poskytuje jasnou cestovní mapu pro efektivní výuku, hodnocení a žákovské mistrovství.",
    category: "planning",
    categories: ["planning"],
    gemUrl: "https://www.edugems.ai/gem/standards-unpacker"
  },
  "station-rotations": {
    slug: "station-rotations",
    emoji: "🔄",
    title: "Station Rotations",
    titleCs: "Stanoviště",
    shortDescCs: "Plánování rotací stanovišť.",
    descriptionCs: "Tento Gem pomáhá rychle navrhnout soudržnou, výzkumem podloženou hodinu se stanovišti v souladu s osvědčenými postupy blended learningu. Ideální pro vytváření poutavých, diferencovaných hodin, generuje kompletně rozpracovaný plán hodiny včetně podrobných profilů stanovišť, průběhu a rutin, strategií diferenciace a dat a tipů pro škálování a implementaci.",
    category: "planning",
    categories: ["planning"],
    gemUrl: "https://www.edugems.ai/gem/station-rotations"
  },
  "unit-plan": {
    slug: "unit-plan",
    emoji: "📋",
    title: "Unit Plan",
    titleCs: "Plán jednotky",
    shortDescCs: "Souvislá výuková jednotka s cíli a hodinami.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit podrobný, na standardy navázaný plán jednotky pro efektivní zmapování učební cesty vašich žáků. Výsledný plán je komplexní, jasně formátovaný a obsahuje nezbytné součásti jako učební cíle, standardy, klíčovou slovní zásobu a doporučený časový harmonogram.",
    category: "planning",
    categories: ["planning"],
    gemUrl: "https://www.edugems.ai/gem/unit-plan"
  },
  "coloring-page-maker": {
    slug: "coloring-page-maker",
    emoji: "🖍️",
    title: "Coloring Page Maker",
    titleCs: "Tvůrce omalovánek",
    shortDescCs: "Generování omalovánek pro výuku.",
    descriptionCs: "Tento Gem pomáhá generovat kvalitní, vlastní omalovánky přizpůsobené vašemu kurikulu nebo tématu. Jako váš „kreativní společník pro omalovánky\“ vytváří bezpečné, čisté linkové kresby na čistě bílém pozadí, ideální pro tisk a použití ve třídě k relaxaci, odměně nebo tematickému upevnění.",
    category: "materials",
    categories: ["materials"],
    gemUrl: "https://www.edugems.ai/gem/coloring-page-maker"
  },
  "decodable-texts": {
    slug: "decodable-texts",
    emoji: "📖",
    title: "Decodable Texts",
    titleCs: "Dekódovatelné texty",
    shortDescCs: "Texty pro nácvik čtení.",
    descriptionCs: "Tento Gem pomáhá rychle napsat vlastní, poutavý a přístupný dekódovatelný text v souladu s vědou o čtení. Ideální pro budování základních čtenářských dovedností a sebevědomí vytvářením textu, který je přísně kontrolovaný, cílí na konkrétní fonologickou dovednost a používá pouze dříve naučené vzory a frekventovaná slova.",
    category: "materials",
    categories: ["materials", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/decodable-texts"
  },
  "discussion-prompts": {
    slug: "discussion-prompts",
    emoji: "🗣️",
    title: "Discussion Prompts",
    titleCs: "Diskusní podněty",
    shortDescCs: "Podněty pro diskuzi ve třídě.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit sadu hutných, otevřených otázek určených ke stimulaci smysluplných třídních diskusí. Otázky jsou navrženy tak, aby byly přiměřené ročníku, podporovaly divergentní myšlení, zvaly k více perspektivám a vyžadovaly od žáků hluboké ponoření do obsahu s využitím důkazů.",
    category: "materials",
    categories: ["materials", "engagement", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/discussion-prompts"
  },
  "graphic-novel-maker": {
    slug: "graphic-novel-maker",
    emoji: "🗯️",
    title: "Graphic Novel Maker",
    titleCs: "Scénárista komiksů",
    shortDescCs: "Scénáře pro komiksy a grafické romány v NotebookLM.",
    descriptionCs: "Tento Gem pomáhá převést libovolný příběh, článek nebo jiný zdrojový text do profesionálně zpracovaného scénáře pro komiks nebo grafický román. V roli zkušeného komiksového scénáristy a vizuálního režiséra vytváří přehlednou strukturu vhodnou pro snadný převod do vizuální podoby v NotebookLM, hlídá návaznost děje i vzhledu postav opakováním jejich popisů v každém panelu a navrhuje rozvržení scén v kinematografickém formátu 16:9 včetně působivé titulní stránky.",
    category: "materials",
    categories: ["materials", "literacy"],
    gemUrl: "https://gemini.google.com/gem/164vmd5wgZAT2-GHMFcHOtz1nJBvFnH4H?usp=sharing"
  },
  "guided-notes": {
    slug: "guided-notes",
    emoji: "🧭",
    title: "Guided Notes",
    titleCs: "Řízené poznámky",
    shortDescCs: "Strukturované poznámky pro žáky.",
    descriptionCs: "Tento Gem pomáhá rychle přeměnit libovolný zdrojový text (přepis videa, článek, povídku nebo kapitolu učebnice) na komplexní řízené poznámky fungující jako cenný studijní materiál. Na rozdíl od jednoduchých odrážkových seznamů vytváří vysoce strukturované vyprávěcí shrnutí odrážející průběh a hutnost původního materiálu, včetně doplňovaček s frekventovanými výrazy, syntetizačních reflexních otázek a klíče pro učitele.",
    category: "materials",
    categories: ["materials", "support"],
    gemUrl: "https://www.edugems.ai/gem/guided-notes"
  },
  "informational-text": {
    slug: "informational-text",
    emoji: "📃",
    title: "Informational Text",
    titleCs: "Informační text",
    shortDescCs: "Tvorba informačních textů pro výuku.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit jasný, podrobný a fakticky přesný informační text přeměnou složitého akademického obsahu na přístupný a poutavý formát pro žáky K-12. Ideální pro generování vlastních čtených pasáží těsně navázaných na učební cíl a přizpůsobených konkrétním čtenářským potřebám žáků.",
    category: "materials",
    categories: ["materials", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/informational-text"
  },
  "reading-list": {
    slug: "reading-list",
    emoji: "📗",
    title: "Reading List",
    titleCs: "Seznam četby",
    shortDescCs: "Doporučené seznamy knih.",
    descriptionCs: "Tento Gem pomáhá rychle sestavit poutavý, na kurikulum navázaný seznam četby tím, že zajišťuje, že všechny doporučené knihy, články a texty jsou přesné, publikované díla podporující vaše výukové cíle. Ideální pro navrhování literárních kroužků, výběru pro samostatné čtení nebo komplexních souborů textů, které roznítí lásku ke čtení u všech žáků.",
    category: "materials",
    categories: ["materials", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/reading-list"
  },
  "sentence-starters": {
    slug: "sentence-starters",
    emoji: "✍️",
    title: "Sentence Starters",
    titleCs: "Začátky vět",
    shortDescCs: "Začátky vět pro psaní a diskuzi.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit sadu konkrétních, relevantních a ročníku přiměřených začátků vět pro lešení akademického jazyka pro vaše žáky. Ideální pro zlepšení žákovského sebevědomí a akademického výkonu v psaní a cílené diskuzi tím, že jim pomáhá efektivně artikulovat nápady, používat důkazy nebo přecházet mezi myšlenkami.",
    category: "materials",
    categories: ["materials", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/sentence-starters"
  },
  "slideshow-maker": {
    slug: "slideshow-maker",
    emoji: "🖼️",
    title: "Slideshow Maker",
    titleCs: "Tvůrce prezentací",
    shortDescCs: "Tvorba slideshow prezentací.",
    descriptionCs: "Tento Gem pomáhá přeměnit surové informace – jako články, poznámky nebo nahrané soubory – na poutavé, kompletní prezentace. Jako expertní návrhář prezentací a vizuální vypravěč využívá funkci Canvas k vygenerování hotového produktu včetně jasných názvů slidů, strukturovaného obsahu, vhodných obrázků a podrobných poznámek pro prezentujícího.",
    category: "materials",
    categories: ["materials"],
    gemUrl: "https://www.edugems.ai/gem/slideshow-maker"
  },
  "song-lyrics": {
    slug: "song-lyrics",
    emoji: "🎵",
    title: "Song Lyrics",
    titleCs: "Texty písní",
    shortDescCs: "Texty písní pro výuku.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit originální, kontextově relevantní texty písní pro přeměnu akademického obsahu na poutavou multimodální učební zkušenost. Ideální pro vytváření zapamatovatelných háčků, nástrojů pro opakování nebo kreativních hodnoticích podnětů, které u žáků rezonují.",
    category: "materials",
    categories: ["materials", "engagement", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/song-lyrics"
  },
  "story-writer": {
    slug: "story-writer",
    emoji: "📖",
    title: "Story Writer",
    titleCs: "Tvůrce příběhů",
    shortDescCs: "Generování příběhů pro výuku.",
    descriptionCs: "Tento Gem pomáhá vytvářet kvalitní, poutavé příběhy přizpůsobené konkrétním potřebám vaší třídy. Jako profesionální spisovatel příběhů a instruktážní návrhář vytváří narativy přísně navázané na vámi specifikovaný ročník, žánr a učební účel (např. výuka o zlaté horečce nebo procvičování inference). Umožňuje nahrát zdrojové materiály nebo připojit soubory z Google Disku pro vedení narativu a zajištění souladu obsahu s kurikulem.",
    category: "materials",
    categories: ["materials", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/story-writer"
  },
  "text-rewriter": {
    slug: "text-rewriter",
    emoji: "✍️",
    title: "Text Rewriter",
    titleCs: "Přepisovač textů",
    shortDescCs: "Příprava textů v různých úrovních obtížnosti.",
    descriptionCs: "Tento Gem pomáhá okamžitě analyzovat a přizpůsobit libovolný text specifickým potřebám vašich žáků. Jako expertní specialista na gramotnost zachovává jádro významu původního materiálu a zároveň umožňuje přesně upravit čtenářskou úroveň, délku, tón, styl, formát a prvky přístupnosti (jako odstranění idiomů nebo členění textu).",
    category: "materials",
    categories: ["materials", "support", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/text-rewriter"
  },
  "video-prompt-generator": {
    slug: "video-prompt-generator",
    emoji: "🎬",
    title: "Video Prompt Generator",
    titleCs: "Generátor videopromptů",
    shortDescCs: "Generování promptů pro tvorbu videí.",
    descriptionCs: "Tento Gem funguje jako váš expertní režisér videopromptů a pomáhá sestavit „perfektní\“ prompt pro nástroje pro generování AI videí jako Veo, Sora a Runway. Kombinuje hluboké znalosti kinematografie (osvětlení, úhly kamery, poměry stran) s inženýrstvím AI promptů k přeměně vágních nápadů na podrobné, vysoce věrné instrukce generující úžasné výsledky.",
    category: "materials",
    categories: ["materials"],
    gemUrl: "https://www.edugems.ai/gem/video-prompt-generator"
  },
  "vocabulary-list": {
    slug: "vocabulary-list",
    emoji: "📋",
    title: "Vocabulary List",
    titleCs: "Slovní zásoba",
    shortDescCs: "Seznamy slovní zásoby pro výuku.",
    descriptionCs: "Tento Gem pomáhá rychle generovat kvalitní materiály slovní zásoby přizpůsobené čtenářské úrovni vašich žáků. Jako užitečný asistent pedagoga vytváří seznamy obsahující slovo, definici přiměřenou ročníku a kontextovou větu ukazující, jak se slovo skutečně používá. Může čerpat slovní zásobu z konkrétního textu, který vložíte nebo nahrajete, nebo generovat relevantní termíny na základě obecného tématu.",
    category: "materials",
    categories: ["materials", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/vocabulary-list"
  },
  "worksheet": {
    slug: "worksheet",
    emoji: "📝",
    title: "Worksheet",
    titleCs: "Pracovní list",
    shortDescCs: "Pracovní listy s úlohami a řešeními.",
    descriptionCs: "Tento Gem pomáhá rychle vytvářet vysoce přizpůsobené pracovní listy pro jakoukoli učební zkušenost, přičemž zajišťuje formátování vhodné pro snadný export do Google Docs nebo jiných textových procesorů. Ideální pro návrh materiálů k procvičování, opakování nebo hodnocení přesně navázaných na vaše výukové cíle. Povedete s Gemini spolupracující rozhovor – začnete uvedením cíle pracovního listu, cílového obsahu (standard, téma nebo cíl), ročníku žáků, typů otázek/položek (např. výběr z možností, krátká odpověď) a požadované úrovně obtížnosti nebo počtu aktivit. Gemini vás provede procesem, položí upřesňující otázky a nabídne návrhy k vylepšení.",
    category: "materials",
    categories: ["materials"],
    gemUrl: "https://www.edugems.ai/gem/worksheet"
  },
  "2-truths-a-lie-game": {
    slug: "2-truths-a-lie-game",
    emoji: "🫢",
    title: "2 Truths & a Lie Game",
    titleCs: "Hra 2 pravdy a lež",
    shortDescCs: "Výroky ke konkrétnímu tématu – žáci hádají lež.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit vlastní kolo hry „Dvě pravdy a lež\“ pro libovolné téma. Ideální pro podporu zapojení žáků, kritického myšlení a diagnostického opakování generováním tří výroků přiměřených věku – dvou faktů a jedné věrohodné, přesvědčivé lži – k prověření žákovského porozumění a zacílení na běžné omyly.",
    category: "engagement",
    categories: ["engagement"],
    gemUrl: "https://www.edugems.ai/gem/2-truths-a-lie-game"
  },
  "20-questions-game": {
    slug: "20-questions-game",
    emoji: "🤔",
    title: "20 Questions Game",
    titleCs: "Hra 20 otázek",
    shortDescCs: "Klasická hra 20 otázek pro výuku.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit vlastní, poutavé a náročné kolo hry „20 otázek\“. Ideální pro podporu kritického myšlení, diagnostického opakování a systematického dotazování, když žáci spolupracují na hádání klíčového slova, významné osobnosti nebo základního konceptu z vaší hodiny.",
    category: "engagement",
    categories: ["engagement"],
    gemUrl: "https://www.edugems.ai/gem/20-questions-game"
  },
  "ai-debate": {
    slug: "ai-debate",
    emoji: "⚖️",
    title: "AI Debate",
    titleCs: "AI debata",
    shortDescCs: "Debata s AI na různá témata.",
    descriptionCs: "Tento Gem umožňuje vašim žákům zapojit se do náročné, strukturované debaty bod proti bodu s expertní AI. Ideální pro podporu kritického myšlení, logické argumentace a respektující diskuse, protože žáci musí přímo reagovat na stručný, promyšlený protichůdný názor.",
    category: "engagement",
    categories: ["engagement", "student"],
    gemUrl: "https://www.edugems.ai/gem/ai-debate"
  },
  "ai-role-play-interview": {
    slug: "ai-role-play-interview",
    emoji: "🎙️",
    title: "AI Role Play Interview",
    titleCs: "AI role-play rozhovor",
    shortDescCs: "Simulace rozhovorů s AI.",
    descriptionCs: "Tento Gem umožňuje vašim žákům vést třídní rozhovor s expertní AI, která může ztělesnit personu libovolné osoby, postavy, zvířete nebo předmětu (např. koala, římský centurion nebo historická osobnost). Ideální pro podporu zkoumání obsahu a kritického myšlení ve vysoce interaktivním formátu.",
    category: "engagement",
    categories: ["engagement", "student"],
    gemUrl: "https://www.edugems.ai/gem/ai-role-play-interview"
  },
  "classroom-taboo-game": {
    slug: "classroom-taboo-game",
    emoji: "🤐",
    title: "Classroom Taboo Game",
    titleCs: "Třídní hra Taboo",
    shortDescCs: "Hra Taboo přizpůsobená výuce.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat zábavné a náročné kolo hry „Třídní Taboo\“ pro libovolné téma. Ideální pro upevnění klíčové slovní zásoby a konceptů, protože žáci musí kriticky myslet, aby uhodli tajné slovo na základě nápověd od Gemini, přičemž se vyhýbají seznamu běžných, „tabu\“ souvisejících výrazů.",
    category: "engagement",
    categories: ["engagement"],
    gemUrl: "https://www.edugems.ai/gem/classroom-taboo-game"
  },
  "cyoa-story": {
    slug: "cyoa-story",
    emoji: "🔠",
    title: "CYOA Story",
    titleCs: "Příběh typu Vyber si vlastní dobrodružství",
    shortDescCs: "Interaktivní příběhy s volbami.",
    descriptionCs: "Tento Gem přeměňuje standardní hodiny na ponořující, interaktivní narativy, které umožňují žákům „prožít\“ historické události, vědecké procesy nebo literární scénáře. Jako expertní průvodce vzdělávacím dobrodružstvím usnadňuje kolo za kolem hru „Vyber si vlastní dobrodružství\“ přísně navázanou na vaše učební cíle a ročník, zajišťuje, že zábava slouží pedagogickému účelu.",
    category: "engagement",
    categories: ["engagement", "student"],
    gemUrl: "https://www.edugems.ai/gem/cyoa-story"
  },
  "emoji-definition-game": {
    slug: "emoji-definition-game",
    emoji: "📓",
    title: "Emoji Definition Game",
    titleCs: "Hra emoji definice",
    shortDescCs: "Hádání pojmů pomocí emoji.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit zábavnou, vizuální a vysoce poutavou hru „Emoji definice\“ pro upevnění klíčové slovní zásoby, významných osobností nebo základních konceptů z libovolného tématu. Ideální pro podporu nadšené třídní diskuse a opakování prostřednictvím zapamatovatelné, kolaborativní hádanky.",
    category: "engagement",
    categories: ["engagement"],
    gemUrl: "https://www.edugems.ai/gem/emoji-definition-game"
  },
  "gamified-learning": {
    slug: "gamified-learning",
    emoji: "🎲",
    title: "Gamified Learning",
    titleCs: "Gamifikované učení",
    shortDescCs: "Gamifikace výukových aktivit.",
    descriptionCs: "Tento Gem pomáhá rychle navrhnout jedinečnou, kreativní herní učební zkušenost pro gamifikaci nadcházející hodiny nebo opakování obsahu. Ideální pro podporu zapojení a motivace žáků slaďováním herních mechanik s vašimi učebními cíli a poskytováním podrobných instrukcí k materiálům, postupům učitele a žákovským instrukcem.",
    category: "engagement",
    categories: ["engagement"],
    gemUrl: "https://www.edugems.ai/gem/gamified-learning"
  },
  "historical-what-if": {
    slug: "historical-what-if",
    emoji: "⌛",
    title: "Historical What If?",
    titleCs: "Historické Co kdyby?",
    shortDescCs: "Alternativní historické scénáře.",
    descriptionCs: "Tento Gem pomáhá učitelům společenských věd vytvářet náročné, věrohodné a poutavé scénáře „alternativní historie\“ pro výuku kauzality a historického významu. Jako „Chrono-Shift historik\“ přesahuje jednoduché vyprávění a generuje komplexní zprávu zakotvující fikci v realitě, vytváří hlubokou analýzu vlnových efektů napříč společností, ekonomikou a geopolitikou.",
    category: "engagement",
    categories: ["engagement"],
    gemUrl: "https://www.edugems.ai/gem/historical-what-if"
  },
  "jeopardy-game": {
    slug: "jeopardy-game",
    emoji: "❓",
    title: "Jeopardy Game",
    titleCs: "Kvíz Jeopardy",
    shortDescCs: "Otázky a kategorie ve stylu Jeopardy.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat kompletní obsah pro opakovací hru ve stylu Jeopardy pro gamifikaci akademického obsahu a maximalizaci zapojení žáků. Funguje jako architekt herní show a zajišťuje, že kategorie jsou relevantní, otázky odpovídají vašim standardům nebo zdrojovému textu a obtížnost logicky postupuje od 100 do 500 bodů.",
    category: "engagement",
    categories: ["engagement"],
    gemUrl: "https://www.edugems.ai/gem/jeopardy-game"
  },
  "readers-theater": {
    slug: "readers-theater",
    emoji: "🎭",
    title: "Reader's Theater",
    titleCs: "Drama – čtení rolí",
    shortDescCs: "Scénky a role pro dramatické čtení.",
    descriptionCs: "Tento Gem pomáhá přeměnit konkrétní téma, text nebo koncept na poutavý scénář pro čtení rolí pro budování čtenářské plynulosti a porozumění. Jako expertní specialista na gramotnost zajišťuje, že scénáře jsou vývojově přiměřené, přesně odrážejí předmět a poskytují jasné role podporující výraz bez vyžadování memorování nebo rekvizit.",
    category: "engagement",
    categories: ["engagement", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/readers-theater"
  },
  "story-cowriter": {
    slug: "story-cowriter",
    emoji: "✍️",
    title: "Story Co-Writer",
    titleCs: "Spolutvůrce příběhů",
    shortDescCs: "Společné psaní příběhů s AI.",
    descriptionCs: "Tento Gem usnadňuje kolaborativní aktivitu „round robin\“ nebo „řetězového psaní\“ s vaší třídou. Jako „kreativní spolutvůrce\“ píše střídavě příběh po částech se žáky. Tento přístup povzbuzuje kreativitu, modeluje dobré psací návyky a zajišťuje, že narativ plyne logicky při zachování vývojové přiměřenosti.",
    category: "engagement",
    categories: ["engagement", "student", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/story-cowriter"
  },
  "accommodation-suggestions": {
    slug: "accommodation-suggestions",
    emoji: "🔑",
    title: "Accommodation Suggestions",
    titleCs: "Návrhy úprav",
    shortDescCs: "Návrhy úprav pro žáky se SVP.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat sadu konkrétních, na důkazech založených úprav a modifikací pro žáka s učebními potřebami. Návrhy vycházejí z principů diferenciace a univerzálního designu pro učení (UDL), jsou vývojově přiměřené a proveditelné pro implementaci ve třídě.",
    category: "support",
    categories: ["support"],
    gemUrl: "https://www.edugems.ai/gem/accommodation-suggestions"
  },
  "ai-tutor": {
    slug: "ai-tutor",
    emoji: "🧑‍🏫",
    title: "AI Tutor",
    titleCs: "AI tutor",
    shortDescCs: "Bezpečný AI tutor pro žáky.",
    descriptionCs: "Tento Gem funguje jako sokratovský a povzbuzující studijní partner, který pomáhá žákům rozvíjet hluboké porozumění a dovednosti. Trpělivě provádí žáky strukturovaným učebním procesem – od diagnostiky jejich současných znalostí po podporu cílenými otázkami – přísně se vyhýbá přímým odpovědím, aby zachoval akademickou čestnost a aktivní myšlení. Žák jednoduše zahájí konverzaci o domácím úkolu, projektu nebo studijním tématu. Gemini pak provede personalizovaným procesem: nejprve diagnostikuje potřeby, pak vytvoří plán a nakonec použije „sokratovskou smyčku“ otevřených otázek a užitečných podnětů, aby žákům pomohl řešit problémy a zvládnout koncepty samostatně.",
    category: "support",
    categories: ["support", "student"],
    gemUrl: "https://www.edugems.ai/gem/ai-tutor"
  },
  "alt-text": {
    slug: "alt-text",
    emoji: "💬",
    title: "Alt Text",
    titleCs: "Alternativní text",
    shortDescCs: "Generování alt textů pro obrázky.",
    descriptionCs: "Tento Gem pomáhá generovat přesný, kontextově uvědomělý a WCAG-souladný alternativní text pro obrázky. Jako expertní specialista na přístupnost zajišťuje inkluzivitu vašeho obsahu tím, že sděluje skutečnou funkci a význam vizuálních médií – spíše než jen popis vzhledu – což ho činí ideálním pro prezentace, webové stránky, sociální média a třídní materiály.",
    category: "support",
    categories: ["support"],
    gemUrl: "https://www.edugems.ai/gem/alt-text"
  },
  "alternate-assessment": {
    slug: "alternate-assessment",
    emoji: "🎚️",
    title: "Alternate Assessment",
    titleCs: "Alternativní hodnocení",
    shortDescCs: "Alternativní formy hodnocení.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat kvalitní alternativní verze vašich stávajících kvízů nebo testů. Jako podporující asistent pedagoga zajišťuje, že nová verze zachovává stejné základní učební cíle jako originál při úpravě formátu pro opravné termíny, náhradní termíny nebo diferenciaci (např. úprava obtížnosti nebo přidání úprav).",
    category: "support",
    categories: ["support", "assessment"],
    gemUrl: "https://www.edugems.ai/gem/alternate-assessment"
  },
  "behavior-intervention": {
    slug: "behavior-intervention",
    emoji: "🚦",
    title: "Behavior Intervention",
    titleCs: "Behaviorální intervence",
    shortDescCs: "Strategie pro práci s chováním.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit sadu konkrétních, relevantních a ročníku přiměřených strategií behaviorální intervence pro cokoli od nízké úrovně odvádění pozornosti po významné behaviorální potřeby. Návrhy jsou formulovány v jazyce založeném na silných stránkách a jsou v souladu s osvědčenými postupy jako trauma-informovaná výuka a proaktivní intervence pro zlepšení učebních výsledků.",
    category: "support",
    categories: ["support"],
    gemUrl: "https://www.edugems.ai/gem/behavior-intervention"
  },
  "common-misconceptions": {
    slug: "common-misconceptions",
    emoji: "❌",
    title: "Common Misconceptions",
    titleCs: "Časté omyly",
    shortDescCs: "Identifikace a řešení běžných omylů.",
    descriptionCs: "Tento Gem pomáhá rychle identifikovat běžné žákovské omyly související s konkrétním obsahem a poskytuje cílené, na důkazech založené výukové strategie pro jejich řešení. Ideální pro proaktivní diagnostické hodnocení a zajištění, že vaše výuka je zaměřena na skutečné učební překážky, kterým vaši žáci čelí.",
    category: "support",
    categories: ["support"],
    gemUrl: "https://www.edugems.ai/gem/common-misconceptions"
  },
  "concept-analogies": {
    slug: "concept-analogies",
    emoji: "⚖️",
    title: "Concept Analogies",
    titleCs: "Pojmové analogie",
    shortDescCs: "Analogie pro vysvětlení pojmů.",
    descriptionCs: "Tento Gem pomáhá překlenout propast mezi existujícími předchozími znalostmi žáků a náročnými novými akademickými koncepty. Funguje jako specialista na kognitivní vědu a generuje 3 odlišné, ročníku přiměřené analogie, které mapují obtížnou myšlenku na známý scénář nebo zájem. Výstupní produkt zajišťuje přesné pojmové mapování při jasné identifikaci omezení srovnání, aby nedocházelo k vytváření omylů.",
    category: "support",
    categories: ["support", "stem"],
    gemUrl: "https://www.edugems.ai/gem/concept-analogies"
  },
  "differentiation-strategies": {
    slug: "differentiation-strategies",
    emoji: "🔠",
    title: "Differentiation Strategies",
    titleCs: "Strategie diferenciace",
    shortDescCs: "Strategie pro diferenciaci výuky.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit sadu konkrétních, na důkazech založených strategií diferenciace a úprav přizpůsobených hodině, hodnocení nebo učebnímu materiálu. Ideální pro zajištění, že uspokojíte potřeby všech žáků – ať už se specifickými poruchami učení, vícejazyčnými žáky nebo žáky pracujícími pod nebo nad úrovní ročníku – slaďováním s principy UDL a osvědčenými postupy.",
    category: "support",
    categories: ["support"],
    gemUrl: "https://www.edugems.ai/gem/differentiation-strategies"
  },
  "ell-conversation": {
    slug: "ell-conversation",
    emoji: "💬",
    title: "ELL Conversation",
    titleCs: "Konverzace pro ELL",
    shortDescCs: "Jazyková podpora pro žáky s odlišným mateřským jazykem.",
    descriptionCs: "Tento Gem funguje jako podporující a trpělivý tutor angličtiny, pomáhá žákům procvičovat konverzaci a překlenuje propast mezi jejich mateřským jazykem a angličtinou. Umí přizpůsobit slovní zásobu a rychlost jakékoli úrovni pokročilosti (WIDA 1–6), využívá žákův první jazyk (L1) pro nastavení a obtížná vysvětlení při maximalizaci imerze do angličtiny během konverzace.",
    category: "support",
    categories: ["support", "student", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/ell-conversation"
  },
  "iep504-smart-goal": {
    slug: "iep504-smart-goal",
    emoji: "🎯",
    title: "IEP/504 SMART Goal",
    titleCs: "SMART cíle pro IEP/504",
    shortDescCs: "Konkrétní cíle pro IVP.",
    descriptionCs: "Tento Gem funguje jako podporující mentor pro učitele speciální pedagogiky, učitele všeobecného vzdělávání a specialisty, pomáhá přeměnit surová žákovská data – dokonce i „chaotický výlev\" – na právně správné, na silných stránkách založené SMART cíle. Zajišťuje, že cíle jsou Specifické, Měřitelné, Dosažitelné, Relevantní a Časově vymezené, a zároveň navrhuje relevantní úpravy a konkrétní metody sběru dat pro sledování pokroku.",
    category: "support",
    categories: ["support"],
    gemUrl: "https://www.edugems.ai/gem/iep504-smart-goal"
  },
  "learner-scaffolds": {
    slug: "learner-scaffolds",
    emoji: "🪜",
    title: "Learner Scaffolds",
    titleCs: "Opory pro učení",
    shortDescCs: "Scaffolding pro žáky.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit strukturovanou, komplexní a na důkazech založenou sadu učebních opor pokrývajících celý učební cyklus (přední, distribuované a zadní podpory). Ideální pro navrhování podpor, které jsou vývojově přiměřené a těsně navázané na konkrétní ročník a učební cíl/dovednost, zajišťuje, že všichni žáci mohou obsahu přistupovat a zvládnout ho.",
    category: "support",
    categories: ["support"],
    gemUrl: "https://www.edugems.ai/gem/learner-scaffolds"
  },
  "ohio-idea-guidance": {
    slug: "ohio-idea-guidance",
    emoji: "🧭",
    title: "Ohio IDEA Guidance",
    titleCs: "Ohio IDEA návod",
    shortDescCs: "Návod pro speciální vzdělávání (Ohio IDEA).",
    descriptionCs: "Tento Gem pomáhá rychle odpovídat na provozní a compliance otázky zakotvené v ohijském a federálním právu speciálního vzdělávání. Ideální pro vytváření praktických artefaktů jako kontrolní seznamy, časové osy, oznámení rodičům a návrhy jazyka IEP, které udržují okresy v souladu s požadavky, s použitím specifických ohijských termínů (ETR, PR-01) a citací.",
    category: "support",
    categories: ["support"],
    gemUrl: "https://www.edugems.ai/gem/ohio-idea-guidance"
  },
  "project-breakdown": {
    slug: "project-breakdown",
    emoji: "📋",
    title: "Project Breakdown",
    titleCs: "Rozdělení projektu",
    shortDescCs: "Rozdělení projektu na kroky.",
    descriptionCs: "Tento Gem funguje jako vřelý, organizovaný mentor pro žáky čelící velkým, ohromujícím úkolům. Pomáhá žákům zvládat jejich pracovní zátěž rozdělením složitých projektů na zvládnutelné „mikrokroky\“ s jasným časovým harmonogramem. Klíčově dodržuje „průvodcovskou\“ zábradlí, zajišťuje, že poskytuje opory, osnovy a strukturu, místo aby za žáka psal obsah.",
    category: "support",
    categories: ["support", "student"],
    gemUrl: "https://www.edugems.ai/gem/project-breakdown"
  },
  "re-level-text": {
    slug: "re-level-text",
    emoji: "🔀",
    title: "Re-level Text",
    titleCs: "Přeúrovňování textů",
    shortDescCs: "Texty v různých úrovních obtížnosti.",
    descriptionCs: "Tento Gem pomáhá rychle přeúrovnit daný text nebo pasáž pro přesné přizpůsobení specifickým čtenářským potřebám žáka, souboru dovedností nebo učebnímu cíli. Ideální pro zajištění, že váš akademický obsah je přístupný všem žákům úpravou slovní zátěže, složitosti vět a celkové struktury při zachování původního významu.",
    category: "support",
    categories: ["support"],
    gemUrl: "https://www.edugems.ai/gem/re-level-text"
  },
  "restorative-justice-circle": {
    slug: "restorative-justice-circle",
    emoji: "🤝",
    title: "Restorative Justice Circle",
    titleCs: "Kruh restorativní justice",
    shortDescCs: "Restorativní přístupy ve třídě.",
    descriptionCs: "Tento Gem pomáhá efektivně usnadňovat řešení konfliktů vedením žáků strukturovaným restorativním procesem. Jako zkušený koordinátor restorativní justice generuje kompletní scénář pro facilitátora určený k napravení újmy a obnovení vztahů. Zajišťuje, že všechny hlasy jsou slyšeny v bezpečném, neutrálním prostředí a přesouvá pozornost od trestu k porozumění a dohodě.",
    category: "support",
    categories: ["support", "professional"],
    gemUrl: "https://www.edugems.ai/gem/restorative-justice-circle"
  },
  "social-stories": {
    slug: "social-stories",
    emoji: "📖",
    title: "Social Stories",
    titleCs: "Sociální příběhy",
    shortDescCs: "Sociální příběhy pro žáky.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat konkrétní, vysoce přizpůsobenou sociální příběh pro pomoc žákovi porozumět a připravit se na konkrétní událost nebo situaci. Ideální pro proaktivní sociálně-emoční intervenci, pomáhá žákům porozumět očekávanému sledu událostí, poskytuje jasný výsledek a stanovuje pozitivní strategii zvládání.",
    category: "support",
    categories: ["support"],
    gemUrl: "https://www.edugems.ai/gem/social-stories"
  },
  "vocabulary-tiers": {
    slug: "vocabulary-tiers",
    emoji: "🪜",
    title: "Vocabulary Tiers",
    titleCs: "Úrovně slovní zásoby",
    shortDescCs: "Třídění slovní zásoby podle obtížnosti.",
    descriptionCs: "Tento Gem funguje jako váš podporující kouč gramotnosti a spolupedagog, pomáhá analyzovat výukové texty pomocí modelu Beck, McKeown a Kucan. Shrnuje váš text a kategorizuje slova do úrovně 1 (základní), úrovně 2 (vysoká využitelnost akademická) a úrovně 3 (oborově specifická), což vám umožňuje přesně určit, která slova učit pro maximální žákovské porozumění.",
    category: "support",
    categories: ["support", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/vocabulary-tiers"
  },
  "act-english-generator": {
    slug: "act-english-generator",
    emoji: "📓",
    title: "ACT English Generator",
    titleCs: "Generátor ACT English",
    shortDescCs: "Generování cvičení ACT English.",
    descriptionCs: "Tento Gem pomáhá hladce vložit přípravu na ACT English do vašeho stávajícího kurikula bez narušení průběhu hodin. Jako expertní specialista na integraci kurikula ACT generuje kvalitní, standardizované otázky založené na vašich konkrétních obsahových tématech (např. první světová válka, mitóza, Velký Gatsby), umožňuje „skrytou\“ přípravu na testy v hodinách dějepisu, přírodopisu nebo literatury.",
    category: "assessment",
    categories: ["assessment", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/act-english-generator"
  },
  "act-math-generator": {
    slug: "act-math-generator",
    emoji: "🔢",
    title: "ACT Math Generator",
    titleCs: "Generátor ACT Math",
    shortDescCs: "Generování cvičení ACT Math.",
    descriptionCs: "Tento Gem pomáhá hladce vložit přípravu na ACT Math do libovolného předmětu – od fyzikálních laboratoří po analýzu historických dat. Jako expertní specialista na integraci kurikula ACT Math generuje kvalitní, standardizované úlohy propojující vaše konkrétní třídní témata s oficiálními oblastmi ACT matematiky (algebra, geometrie, statistika atd.), využívá deskriptivní geometrii tam, kde vizuální diagramy nejsou možné.",
    category: "assessment",
    categories: ["assessment", "stem"],
    gemUrl: "https://www.edugems.ai/gem/act-math-generator"
  },
  "act-reading-generator": {
    slug: "act-reading-generator",
    emoji: "📖",
    title: "ACT Reading Generator",
    titleCs: "Generátor ACT Reading",
    shortDescCs: "Generování cvičení ACT Reading.",
    descriptionCs: "Tento Gem pomáhá hladce vložit přípravu na ACT Reading do vašeho stávajícího kurikula bez narušení průběhu hodin. Jako expertní specialista na integraci kurikula ACT generuje kvalitní, standardizované pasáže a otázky založené na vašich konkrétních obsahových tématech (např. Hedvábná stezka, kovalentní vazby, Jako zabít ptáčka), umožňuje cílenou přípravu na testy v libovolném předmětu.",
    category: "assessment",
    categories: ["assessment", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/act-reading-generator"
  },
  "assessment-data-analyzer": {
    slug: "assessment-data-analyzer",
    emoji: "📊",
    title: "Assessment Data Analyzer",
    titleCs: "Analýza dat z testů",
    shortDescCs: "Analýza výsledků testů a trendů.",
    descriptionCs: "Tento Gem pomáhá analyzovat výsledky žákovských hodnocení pro odvození konkrétních pedagogických poznatků a určení úrovní žákovských výkonů. Funguje jako expertní diagnostický specialista a zajišťuje, že vaše analýza dat vede přímo k využitelným strategiím jako diferenciace, skupinování a cílené plánování hodin, spíše než jen k seznamu skóre.",
    category: "assessment",
    categories: ["assessment"],
    gemUrl: "https://www.edugems.ai/gem/assessment-data-analyzer"
  },
  "dok-analysis": {
    slug: "dok-analysis",
    emoji: "📊",
    title: "DOK Analysis",
    titleCs: "DOK analýza",
    shortDescCs: "Analýza úrovní DOK.",
    descriptionCs: "Tento Gem pomáhá rychle analyzovat libovolné hodnocení pro určení úrovně hloubky znalostí (DOK) u každé otázky pomocí rámce DOK 1–4. Ideální pro získání jasného porozumění kognitivním nárokům vašich materiálů, identifikaci klíčových sloves a zajištění, že vaše hodnocení podporují odpovídající úroveň žákovské náročnosti.",
    category: "assessment",
    categories: ["assessment"],
    gemUrl: "https://www.edugems.ai/gem/dok-analysis"
  },
  "dok-questions": {
    slug: "dok-questions",
    emoji: "❓",
    title: "DOK Questions",
    titleCs: "DOK otázky",
    shortDescCs: "Otázky různých úrovní DOK.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit sadu otázek výslovně navázaných na všechny čtyři úrovně hloubky znalostí (DOK). Ideální pro navrhování náročné třídní diskuse, hodnocení nebo žákovských úkolů, které povzbuzují k postupně hlubšímu myšlení od vybavení (DOK 1) po rozšířené uvažování (DOK 4).",
    category: "assessment",
    categories: ["assessment"],
    gemUrl: "https://www.edugems.ai/gem/dok-questions"
  },
  "exemplar-non-exemplar-responses": {
    slug: "exemplar-non-exemplar-responses",
    emoji: "🔠",
    title: "Exemplar & Non-Exemplar",
    titleCs: "Exemplární a neexemplární odpovědi",
    shortDescCs: "Příklady dobrých a slabých odpovědí.",
    descriptionCs: "Tento Gem pomáhá rychle generovat diferencované modelové žákovské odpovědi, včetně kvalitních (exemplárních) i nekvalitních (neexemplárních), na základě vašeho úkolu a rubriky. Ideální pro ukázání žákům, jak vypadá úspěch, a pomáhá jim identifikovat běžné omyly a chyby před odevzdáním vlastní práce.",
    category: "assessment",
    categories: ["assessment"],
    gemUrl: "https://www.edugems.ai/gem/exemplar-non-exemplar-responses"
  },
  "inaccurate-text": {
    slug: "inaccurate-text",
    emoji: "❌",
    title: "Inaccurate Text",
    titleCs: "Nepřesný text",
    shortDescCs: "Texty s chybami pro kritické čtení.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit podrobný text na libovolné téma obsahující záměrné a ověřitelné chyby pro žáky k identifikaci a opravě. Ideální pro zapojení žáků do identifikace chyb, kritické analýzy a hlubokého opakování obsahu, přeměňuje běžné omyly nebo cvičení v editaci na náročnou aktivitu.",
    category: "assessment",
    categories: ["assessment"],
    gemUrl: "https://www.edugems.ai/gem/inaccurate-text"
  },
  "nwea-map-analysis": {
    slug: "nwea-map-analysis",
    emoji: "🗺️",
    title: "NWEA MAP Analysis",
    titleCs: "Analýza NWEA MAP",
    shortDescCs: "Analýza výsledků NWEA MAP.",
    descriptionCs: "Tento Gem pomáhá rychle analyzovat vaše zprávy NWEA MAP Class Profile pro vygenerování jediného, sjednoceného a využitelného „datového příběhu\“ pro vaši třídu. Ideální pro získání jasného porozumění potřebám vašich žáků identifikací celotřídních trendů, mezipředmětových vzorců a konkrétních žákovských skupin pro diferenciaci, vše strukturované pro okamžité plánování výuky.",
    category: "assessment",
    categories: ["assessment"],
    gemUrl: "https://www.edugems.ai/gem/nwea-map-analysis"
  },
  "rubric": {
    slug: "rubric",
    emoji: "📋",
    title: "Rubric",
    titleCs: "Hodnoticí rubrika",
    shortDescCs: "Rubriky pro hodnocení projektů a prací.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat podrobnou rubriku pro libovolný úkol. Zajišťuje, že kritéria rubriky jsou konkrétní a měřitelná, úrovně výkonu jsou odlišné a celkový design podporuje spravedlivé a transparentní hodnocení pro žáky.",
    category: "assessment",
    categories: ["assessment"],
    gemUrl: "https://www.edugems.ai/gem/rubric"
  },
  "text-dependent-questions": {
    slug: "text-dependent-questions",
    emoji: "❓",
    title: "Text-dependent Questions",
    titleCs: "Textově závislé otázky",
    shortDescCs: "Otázky vázané na text.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat sadu náročných, textově závislých otázek přímo navázaných na libovolný poskytnutý text nebo výukový obsah. Otázky jsou navázány na konkrétní čtenářské standardy, jsou vývojově přiměřené a navrženy pro hodnocení cílených dovedností a znalostí.",
    category: "assessment",
    categories: ["assessment", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/text-dependent-questions"
  },
  "youtube-quiz": {
    slug: "youtube-quiz",
    emoji: "▶️",
    title: "YouTube Quiz",
    titleCs: "YouTube kvíz",
    shortDescCs: "Kvízy k YouTube videím.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit chronologicky uspořádaný kvíz z libovolného poskytnutého přepisu videa. Přeměňuje pasivní konzumaci médií na náročný hodnoticí nástroj, zajišťuje, že otázky sledují časovou osu videa pro podporu sledování žáků v reálném čase a cíleného opakování přesně prezentovaného obsahu.",
    category: "assessment",
    categories: ["assessment"],
    gemUrl: "https://www.edugems.ai/gem/youtube-quiz"
  },
  "act-english-practice": {
    slug: "act-english-practice",
    emoji: "📓",
    title: "ACT English Practice",
    titleCs: "ACT English procvičování",
    shortDescCs: "Procvičování ACT English pro žáky.",
    descriptionCs: "Tento Gem pomáhá žákům připravit se na sekci ACT English tím, že funguje jako expertní interaktivní tutor. Poskytuje individuální procvičovací otázky, okamžitou zpětnou vazbu a jasná vysvětlení napříč klíčovými obsahovými oblastmi včetně tvorby psaní, znalosti jazyka a konvencí standardní angličtiny (gramatika, interpunkce a použití).",
    category: "student",
    categories: ["student", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/act-english-practice"
  },
  "act-math-practice": {
    slug: "act-math-practice",
    emoji: "🔢",
    title: "ACT Math Practice",
    titleCs: "ACT Math procvičování",
    shortDescCs: "Procvičování ACT Math pro žáky.",
    descriptionCs: "Tento Gem pomáhá žákům připravit se na sekci ACT Math tím, že funguje jako expertní tutor. Poskytuje procvičovací otázky, okamžitou zpětnou vazbu a jasná vysvětlení napříč všemi klíčovými obsahovými oblastmi včetně algebry, geometrie, statistiky, číselných operací a trigonometrie.",
    category: "student",
    categories: ["student", "stem"],
    gemUrl: "https://www.edugems.ai/gem/act-math-practice"
  },
  "act-reading-practice": {
    slug: "act-reading-practice",
    emoji: "📖",
    title: "ACT Reading Practice",
    titleCs: "ACT Reading procvičování",
    shortDescCs: "Procvičování ACT Reading pro žáky.",
    descriptionCs: "Tento Gem pomáhá žákům připravit se na sekci ACT Reading tím, že funguje jako interaktivní expertní tutor. Simuluje koučovací sezení v reálném čase generováním krátkých, hutných pasáží napříč různými obory (humanitní vědy, společenské vědy, přírodní vědy a literární narativ) a kladením náročných otázek zaměřených na klíčové myšlenky, řemeslo a strukturu a integraci znalostí.",
    category: "student",
    categories: ["student", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/act-reading-practice"
  },
  "career-explorer": {
    slug: "career-explorer",
    emoji: "💼",
    title: "Career Explorer",
    titleCs: "Průzkumník kariéry",
    shortDescCs: "Objevování povolání podle zájmů.",
    descriptionCs: "Tento Gem pomáhá žákům objevovat a zkoumat potenciální kariérní cesty, které odpovídají jejich jedinečným zájmům, dovednostem a hodnotám. Jako přátelský a povzbuzující průvodce přesahuje jednoduché seznamy a inspiruje k sebereflexi a akci prostřednictvím personalizovaných kariérních návrhů.",
    category: "student",
    categories: ["student"],
    gemUrl: "https://www.edugems.ai/gem/career-explorer"
  },
  "devils-advocate": {
    slug: "devils-advocate",
    emoji: "😈",
    title: "Devil's Advocate",
    titleCs: "Ďáblův advokát",
    shortDescCs: "Kritické zpochybňování argumentů.",
    descriptionCs: "Tento Gem umožňuje vést vysoce náročnou kolaborativní konverzaci s „Ďáblovým advokátem\“. Ideální pro posílení vašich argumentů, identifikaci slepých míst a zvážení tématu z více perspektiv pomocí sokratovské metody, aktivně zpochybňuje předpoklady, vyžaduje důkazy a představuje silné, dobře odůvodněné protinázory.",
    category: "student",
    categories: ["student", "professional"],
    gemUrl: "https://www.edugems.ai/gem/devils-advocate"
  },
  "error-resistant-research": {
    slug: "error-resistant-research",
    emoji: "🏛️",
    title: "Error-Resistant Research",
    titleCs: "Výzkum odolný chybám",
    shortDescCs: "Metody výzkumu s ověřováním zdrojů.",
    descriptionCs: "Tento Gem pomáhá s výzkumem odolným halucinacím, neboť pomáhá rychle najít informace, odpovědět na konkrétní otázky nebo provést podrobný výzkum na libovolné téma. Zaměřuje se na zajištění faktické přesnosti a posílení kritického porozumění, protože každé tvrzení poskytuje transparentní zdroje, úrovně důvěry a explicitní postup krok za krokem.",
    category: "student",
    categories: ["student", "professional"],
    gemUrl: "https://www.edugems.ai/gem/error-resistant-research"
  },
  "student-brainstorming": {
    slug: "student-brainstorming",
    emoji: "🧠",
    title: "Student Brainstorming",
    titleCs: "Žákovský brainstorming",
    shortDescCs: "Kreativní partner pro nápady.",
    descriptionCs: "Tento Gem pomáhá žákům začít a pokročit v jejich konkrétních akademických úkolech tím, že funguje jako kouč kreativní jiskry a účelný akademický myšlenkový partner. Jeho hlavní poslání je cílený brainstorming, zajišťuje, že každá otázka a nápad je odrazovým můstkem vedoucím přímo k finálnímu produktu žáka (např. esej, experiment nebo prototyp).",
    category: "student",
    categories: ["student"],
    gemUrl: "https://www.edugems.ai/gem/student-brainstorming"
  },
  "world-language-conversation": {
    slug: "world-language-conversation",
    emoji: "🉑",
    title: "World Language Conversation",
    titleCs: "Konverzace v cizím jazyce",
    shortDescCs: "Procvičování konverzace v cizím jazyce.",
    descriptionCs: "Tento Gem funguje jako váš imerzní konverzační partner pro cizí jazyky, pomáhá žákům procvičovat mluvení v přirozeném prostředí s nízkým stresem. Jako přátelský kulturní velvyslanec se přizpůsobuje jakékoli úrovni pokročilosti (od začátečníka A1 po pokročilého C2) a přijímá konkrétní personu – jako „Pierre z Paříže\“ nebo „Sofia z Buenos Aires\" – aby byla rolová hra autentická a kulturně bohatá.",
    category: "student",
    categories: ["student", "literacy"],
    gemUrl: "https://www.edugems.ai/gem/world-language-conversation"
  },
  "ai-prompt-architect": {
    slug: "ai-prompt-architect",
    emoji: "📐",
    title: "AI Prompt Architect",
    titleCs: "AI architekt promptů",
    shortDescCs: "Návrh efektivních AI promptů.",
    descriptionCs: "Tento Gem pomáhá vytvořit zcela nový, kvalitní AI prompt od základu. Funguje jako expertní architekt a zajišťuje, že váš prompt je komplexní a dobře strukturovaný, definuje jasnou roli, konkrétní úkol a explicitní pravidla interakce. Ideální pro vytváření vlastních nástrojů produkujících konzistentní, pedagogicky kvalitní interakce pro vaše žáky.",
    category: "professional",
    categories: ["professional"],
    gemUrl: "https://www.edugems.ai/gem/ai-prompt-architect"
  },
  "ai-prompt-doctor": {
    slug: "ai-prompt-doctor",
    emoji: "💊",
    title: "AI Prompt Doctor",
    titleCs: "AI doktor promptů",
    shortDescCs: "Vylepšování existujících promptů.",
    descriptionCs: "Tento Gem pomáhá analyzovat, diagnostikovat a vylepšovat vaše stávající AI prompty, aby byly jasné, efektivní a v souladu s vašimi cíli. Ideální pro přeměnu hrubých nápadů nebo prvních návrhů na kvalitní, strukturované instrukce, které konzistentně produkují požadovaný výstup z AI.",
    category: "professional",
    categories: ["professional"],
    gemUrl: "https://www.edugems.ai/gem/ai-prompt-doctor"
  },
  "class-newsletter": {
    slug: "class-newsletter",
    emoji: "📰",
    title: "Class Newsletter",
    titleCs: "Třídní newsletter",
    shortDescCs: "Newsletter pro rodiče a žáky.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit poutavý a zajímavý třídní newsletter pro žáky, rodiny a školní personál. Ideální pro jasné sdílení důležitých oznámení, oslavu pozoruhodných žákovských úspěchů a uznání vynikajících příspěvků z vaší třídní komunity.",
    category: "professional",
    categories: ["professional"],
    gemUrl: "https://www.edugems.ai/gem/class-newsletter"
  },
  "edugem-generator": {
    slug: "edugem-generator",
    emoji: "💎",
    title: "EduGem Generator",
    titleCs: "Generátor EduGemů",
    shortDescCs: "Tvorba vlastních EduGem promptů.",
    descriptionCs: "Tento Gem pomáhá vytvořit systémové instrukce (prompt) pro vaše vlastní vlastní Gemy. Jako architekt EduGem vás provádí strukturovaným návrhovým procesem, aby zajistil, že váš nový nástroj následuje „zlatý standard\“ architektury nalezené v kolekci GemForge. Pomáhá definovat personu, pravidla interakce a formáty výstupu potřebné k tomu, aby byl váš Gem spolehlivý a efektivní.",
    category: "professional",
    categories: ["professional"],
    gemUrl: "https://www.edugems.ai/gem/edugem-generator"
  },
  "email-to-parents": {
    slug: "email-to-parents",
    emoji: "📧",
    title: "Email to Parents",
    titleCs: "E-mail rodičům",
    shortDescCs: "Profesionální e-maily rodičům.",
    descriptionCs: "Tento Gem pomáhá rychle napsat efektivní a profesionální e-mail zákonným zástupcům konkrétního žáka pro sdílení pozorování, poskytnutí zpětné vazby, aktualizace nebo oslavu úspěchu. Ideální pro zajištění včasné, personalizované a pozitivní komunikace mezi školou a domovem.",
    category: "professional",
    categories: ["professional"],
    gemUrl: "https://www.edugems.ai/gem/email-to-parents"
  },
  "pd-plan": {
    slug: "pd-plan",
    emoji: "💡",
    title: "PD Plan",
    titleCs: "Plán profesního rozvoje",
    shortDescCs: "Plánování profesního vzdělávání.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat podrobný, na dopad zaměřený plán profesního rozvoje přizpůsobený SMART cíli s opatřeními směrovanými jak k žákům, tak k učitelům. Ideální pro pedagogické kouče, kteří potřebují jasnou strategickou sekvenci týdenních koučovacích akcí (např. podněty pro schůzky a hledání při pozorování) a kroků pro učitele, vše v souladu s osvědčenými postupy vzdělávání dospělých.",
    category: "professional",
    categories: ["professional"],
    gemUrl: "https://www.edugems.ai/gem/pd-plan"
  },
  "recommendation-letter": {
    slug: "recommendation-letter",
    emoji: "📬",
    title: "Letter of Rec",
    titleCs: "Doporučující dopis",
    shortDescCs: "Tvorba doporučujících dopisů.",
    descriptionCs: "Tento Gem pomáhá rychle napsat působivý a personalizovaný doporučující dopis pro konkrétního žáka ve vaší třídě. Ideální pro jasné artikulování silných stránek a jedinečných kvalit žáka s relevantními, konkrétními příklady. Zajišťuje, že dopis je přizpůsoben konkrétnímu publiku a účelu (např. přijímací řízení na vysokou školu, stipendijní přihlášky).",
    category: "professional",
    categories: ["professional"],
    gemUrl: "https://www.edugems.ai/gem/recommendation-letter"
  },
  "refresh-knowledge": {
    slug: "refresh-knowledge",
    emoji: "🎓",
    title: "Refresh Knowledge",
    titleCs: "Osvěžení znalostí",
    shortDescCs: "Rychlé osvěžení znalostí před výukou.",
    descriptionCs: "Tento Gem pomáhá rychle vygenerovat jasný, podrobný a fakticky přesný učební plán pro osvěžení znalostí o nadcházející jednotce nebo tématu. Ideální pro získání komplexního porozumění složitému obsahu, neboť je navržen tak, aby pomohl kriticky myslet, představuje více perspektiv a zdůrazňuje souvislosti, chronologii a vztahy příčiny a důsledku.",
    category: "professional",
    categories: ["professional"],
    gemUrl: "https://www.edugems.ai/gem/refresh-knowledge"
  },
  "staff-superhero-image": {
    slug: "staff-superhero-image",
    emoji: "🦸",
    title: "Staff Superhero Image",
    titleCs: "Superhrdinský obrázek personálu",
    shortDescCs: "Vytváření motivujících obrázků pro tým.",
    descriptionCs: "Tento Gem pomáhá oslavit školní personál přeměnou jejich fotografií na kvalitní superhrdinské portréty. Jako váš expertní „školní umělec superhrdinů\“ vytváří pozitivní, ctící a cool obrázky, které zachovávají rozpoznatelnost člena personálu při umístění do dynamických póz. Ideální pro vytváření jedinečných ocenění, plakátů nebo digitálních pozdravů pro učitele, administrátory a podpůrný personál.",
    category: "professional",
    categories: ["professional"],
    gemUrl: "https://www.edugems.ai/gem/staff-superhero-image"
  },
  "math-spiral-review": {
    slug: "math-spiral-review",
    emoji: "🔄",
    title: "Math Spiral Review",
    titleCs: "Matematické spirálové opakování",
    shortDescCs: "Spirálové opakování matematiky.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit vlastní plán spirálového opakování a sadu úloh pro zajištění dlouhodobého uchování dovedností a znalostí žáků. Ideální pro podporu dlouhodobého mistrovství a poskytování diagnostických hodnoticích příležitostí se směsí úloh povzbuzujících žáky k určení nejlepších dovedností a přístupů k použití.",
    category: "stem",
    categories: ["stem"],
    gemUrl: "https://www.edugems.ai/gem/math-spiral-review"
  },
  "math-story-problems": {
    slug: "math-story-problems",
    emoji: "➕",
    title: "Math Story Problems",
    titleCs: "Matematické slovní úlohy",
    shortDescCs: "Slovní úlohy s různou obtížností.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit sadu vlastních slovní úloh pro poskytnutí příležitostí žákům dávat smysl složitým scénářům, aplikovat koncepty na nové problémy a procvičovat strategie řešení problémů. Ideální pro podporu hlubšího pojmového porozumění a aplikace dovedností v matematice.",
    category: "stem",
    categories: ["stem"],
    gemUrl: "https://www.edugems.ai/gem/math-story-problems"
  },
  "science-lab-experiment": {
    slug: "science-lab-experiment",
    emoji: "🧪",
    title: "Science Lab Experiment",
    titleCs: "Vědecký laboratorní experiment",
    shortDescCs: "Návrhy laboratorních experimentů.",
    descriptionCs: "Tento Gem pomáhá rychle vytvořit poutavý, na bádání a jevy založený vědecký laboratorní experiment nebo pokus navázaný na daný koncept a ročník. Ideální pro navrhování zážitkového učení těsně navázaného na vaše požadované učební výsledky s jasnými, podrobnými instrukcemi k materiálům, přípravě a postupům učitele pro spolehlivou implementaci.",
    category: "stem",
    categories: ["stem"],
    gemUrl: "https://www.edugems.ai/gem/science-lab-experiment"
  }
};
